pipeline {
    agent any
    parameters{
        booleanParam(defaultValue: false, description: "Enable service?", name:MyBoolean)
    }
    stages {
        stage('Demo'){
            steps {
                echo "booleanParam is set to : ${params.booleanParam}"
            }
        }
        // stage('Build') {
        //     steps {
        //         sh 'mvn --version'
        //         echo "it worked!!"
        //     }
        // }
        // stage('Test') {
        //     steps {
        //         sh 'mvn test'
        //     }
        //     post {
        //         always {
        //             junit 'target/surefire-reports/*.xml'
        //         }
        //     }
        // }
        // stage('Deliver') {
        //     steps {
        //         sh './jenkins/scripts/deliver.sh'
        //     }
        // }
    }
}
